spring:
  application:
    name: qr-attendance-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/qr_attendance_db
    username: qr_user
    password: vidu

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  flyway:
    enabled: true
